apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-{{ .Values.global.env }}
  namespace: argocd
spec:
  destination:
    namespace: nginx-server-{{ .Values.global.env }}
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 17.1.0
    helm:
      values: |                   # Helm values need to be under the "helm" section
        replicaCount: 2
        service:
          type: LoadBalancer
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
