apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-{{ .Values.global.env }}          # 👈 changed nginx -> wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress-server-{{ .Values.global.env }}    # 👈 changed nginx-server -> wordpress-server
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'           # ✅ still using Bitnami charts
    chart: wordpress                                        # 👈 changed nginx -> wordpress
    targetRevision: 24.2.2                                  # 👈 updated chart version
    helm:
      values: |
        wordpressUsername: user
        wordpressPassword: password
        mariadb:
          enabled: true
          auth:
            rootPassword: rootpassword
            database: bitnami_wordpress
            username: bn_wordpress
            password: wordpresspassword
        service:
          type: LoadBalancer
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true